server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: InfoFilter
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: serieRoute
          uri: lb://serie-service
          predicates:
            - Path=/series/**
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
info:
  app:
    name: gateway-service
    description: Gateway Service created for Final
    version: 2.0.0
